minio:
  # MinIO服务器地址
  endpoint: http://localhost:9000
  # MinIO服务器访问凭据
  accessKey: minioadmin
  secretKey:  minioadmin
  # MinIO桶名称
  bucket: topic
  # MinIO读取路径前缀
  readPath: http://localhost:9000
